version: 2
registries:
  git-git-lai-ai-com:
    type: git
    url: https://git.lai-ai.com
    username: tanjianqing
    password: "${{secrets.GIT_GIT_LAI_AI_COM_PASSWORD}}"
  npm-registry-registry-fe-lai-ai-com:
    type: npm-registry
    url: https://registry.fe.lai-ai.com
    username: "${{secrets.NPM_REGISTRY_REGISTRY_FE_LAI_AI_COM_USERNAME}}"
    password: "${{secrets.NPM_REGISTRY_REGISTRY_FE_LAI_AI_COM_PASSWORD}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "21:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: highlight.js
    versions:
    - 10.5.0
    - 10.6.0
  - dependency-name: ts-jest
    versions:
    - 26.4.4
    - 26.5.0
    - 26.5.2
  - dependency-name: "@types/node"
    versions:
    - 14.14.19
    - 14.14.22
    - 14.14.31
  - dependency-name: "@types/marked"
    versions:
    - 1.2.1
    - 1.2.2
  - dependency-name: "@types/jest"
    versions:
    - 26.0.19
    - 26.0.20
  - dependency-name: sass-loader
    versions:
    - 10.1.0
    - 10.1.1
  - dependency-name: marked
    versions:
    - 1.2.7
    - 1.2.8
  - dependency-name: "@vue/test-utils"
    versions:
    - 1.1.2
  registries:
  - npm-registry-registry-fe-lai-ai-com
  - git-git-lai-ai-com
